# Name of the workflow
name: Hello World Workflow

# Events that trigger this workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, staging]

# Jobs to run
jobs:
  greet:
  # The type of runner to use e.g windows, ubuntu, mac
    runs-on: ubuntu-latest
    # Steps to execute in this job
    steps:
      # Run a single line command
      - name: Hello
        run: echo "Hello World!"